### ISSUE TITLE
Setup kitty-api server

### ISSUE THREAD

**Issue by bradkendall** [kittycash/infrastructure#14]
Setup a kitty-api instance hosted to the public.

Requirements:

https with a valid certificate
`access-control-allow-origin` header set to `http://localhost:6148`
Ensure that preflight (OPTIONS) requests are responding with a 2XX code.

**Comment by jdknives** [comment]
@128-95 what about this ticket? is that Brians work?

**Comment by jdknives** [comment]
@128-95 @briancaine Is this still an up to date ticket? if not please update accordingly or create new tickets for server related work

**Comment by briancaine** [comment]
It just sounds like our staging server, which is set up.

**Comment by briancaine** [comment]
```
$ curl -v -X GET https://staging-api.kittycash.com/v1/ping -o /dev/null 2>&1 | grep -i allow-origin
< Access-Control-Allow-Origin: *
```

@bradkendall Does this work? Can I close this ticket?
